#!/bin/sh
#
# Automatically adds branch name to every commit message.
#
NAME=$(git branch | grep '*' | sed 's/feat\///') 

if [ "$NAME"="master" ] 
then
	echo "" >> "$1"
else
	echo "$NAME"': '$(cat "$1") > "$1"
fi 
