#!/bin/sh
#
# Automatically adds branch name to every commit message.
#
BRANCH_NAME=$(git branch | grep '*' | sed 's/*//' | sed 's/ //' | sed 's/feat\///') 
MSG=$(cat "$1")

if [ "$BRANCH_NAME" = "master" ] || [[ $MSG = $BRANCH_NAME:* ]]
then
	echo "" >> "$1"
else
	echo "$BRANCH_NAME"': '"$MSG" > "$1"
fi 
